/**
 * # Introduction
 * 
 * This repository aims to be an example of what can be achieved 
 * by different third party utilities that works along Terraform.
 * For example the following documentation is auto-generated by [terraform-docs](https://terraform-docs.io)
 *
 * # EC2
 *
 * This folder contains a [Terraform](https://developer.hashicorp.com/terraform) configuration that creates infrastructure on [AWS](https://aws.amazon.com/).
 *
 * *Note: please be aware that this configuration creates real infrastructure so some costs may incur.*
 */
